driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[rsyslog::default]
  - name: relp
    run_list:
      - recipe[rsyslog::client]
    attributes:
      rsyslog:
        use_relp: true
        custom_remote:
            - server: 10.0.0.45
              logs: auth.*,mail.*
              port: 555
              protocol: udp
            - server: 10.1.1.33
              logs: authpriv.*,cron.*,daemon.*
              port: 654
              protocol: tcp
              remote_template: RSYSLOG_SyslogProtocol23Format
  - name: client
    run_list:
      - recipe[rsyslog_test::client]
    attributes:
      rsyslog:
        server_ip: 10.0.0.50
        custom_remote:
            - server: 10.0.0.45
              logs: auth.*,mail.*
              port: 555
              protocol: udp
            - server: 10.1.1.33
              logs: authpriv.*,cron.*,daemon.*
              port: 654
              protocol: tcp
              remote_template: RSYSLOG_SyslogProtocol23Format
  - name: server
    run_list:
      - recipe[rsyslog_test::server]
  - name: input_file_resource
    run_list:
      - recipe[rsyslog_test::input_file_resource]
