name              'rsyslog'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures rsyslog'
version           '9.2.11'
source_url        'https://github.com/sous-chefs/rsyslog'
issues_url        'https://github.com/sous-chefs/rsyslog/issues'
chef_version      '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'linuxmint'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'suse'
supports 'ubuntu'
supports 'zlinux'
